### ISSUE TITLE
Unable to install the nightly bundle on M1 macOS

### ISSUE THREAD

**Issue by potating-potato** [napari/packaging#53] opened 2022-12-16 18:48 UTC
from the error log in the installer:

```
Dec 16 10:45:36 CZIMACOS3562 Installer[9343]: Could not load resource readme: (null)
Dec 16 10:46:03 CZIMACOS3562 installd[6596]: PackageKit: ----- Begin install -----
Dec 16 10:46:31 CZIMACOS3562 installd[6596]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “napari-macOS-arm64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg, PKInstallPackageIdentifier=org.napari.pkg.run_installation, NSLocalizedDescription=An error occurred while running scripts from the package “napari-macOS-arm64.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cnapari-macOS-arm64.pkg\U201d.";
	    NSURL = "file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg";
	    PKInstallPackageIdentifier = "org.napari.pkg.run_installation";
	}
Dec 16 10:46:31 CZIMACOS3562 Installer[9343]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Dec 16 10:46:31 CZIMACOS3562 Installer[9343]: Displaying 'Install Failed' UI.
Dec 16 10:46:31 CZIMACOS3562 Installer[9343]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

before this I also see error message on reinstalling to the same location, so I attempted to install to another location, then I see the above message

**Comment by jaimergp** [comment] 2022-12-19 18:21
Hm, it works on CI: https://github.com/napari/napari/actions/runs/3727226869/jobs/6321295280#step:21:29

Do you have more details in the log file?

> If an error ocurred during the installation, do not close the installer immediately. Before doing so, please inspect the logs by clicking on Window > Installer log or pressing <kbd>⌘</kbd> + <kbd>L</kbd>. In the Detail Level dropdown, choose 'Show All Logs' and click on Save to keep a copy of the contents in a text file. 

Can you also show the contents of the installation? It failed during the main stage, so I wonder what went wrong.

```bash
$ tree "~/Library/napari-*"
```

**Comment by potating-potato** [comment] 2022-12-19 18:31
It tried to install to /Library instead of ~/Library. I removed the installation and rerun it and here's the all logs:
```
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: @(#)PROGRAM:Install  PROJECT:Install-1000
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: @(#)PROGRAM:Installer  PROJECT:Installer-1131
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Hardware: MacBookPro17,1 @ 0 MHz (x 8), 16384 MB RAM
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Running OS Build: macOS 13.0.1 (22A400)
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: USER=zliu
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: COMMAND_MODE=unix2003
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: __CFBundleIdentifier=com.apple.installer
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: LOGNAME=zliu
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.t4sHlyzZeN/Listeners
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: HOME=/Users/zliu
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: SHELL=/bin/zsh
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: TMPDIR=/var/folders/jt/p42nnqj559j6hw4zkcjx8sn00000gq/T/
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: __CF_USER_TEXT_ENCODING=0x1F7:0x0:0x0
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: XPC_SERVICE_NAME=application.com.apple.installer.1152921500312078314.1152921500312078319
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Env: XPC_FLAGS=0x0
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: napari 0.4.17rc4.dev123_gb5696770  Installation Log
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Opened from: /Users/zliu/Downloads/napari-macOS-arm64.pkg
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Product archive /Users/zliu/Downloads/napari-macOS-arm64.pkg trustLevel=350
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: External component packages (5) trustLevel=350
Dec 19 10:29:20 CZIMACOS3562 Installer[24351]: Could not load resource readme: (null)
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: ================================================================================
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: User picked Standard Install
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: Choices selected for installation:
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 	Upgrade: ""
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 	Install: "Install napari"
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 		napari-macOS-arm64.pkg#prepare_installation.pkg : org.napari.pkg.prepare_installation : 0.4.17rc4.dev123_gb5696770
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 	Install: "Create shortcuts"
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 		napari-macOS-arm64.pkg#shortcuts.pkg : org.napari.pkg.shortcuts : 0
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 		napari-macOS-arm64.pkg#run_installation.pkg : org.napari.pkg.run_installation : 0
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 	Upgrade: "Clear the package cache"
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: 		napari-macOS-arm64.pkg#cacheclean.pkg : org.napari.pkg.cacheclean : 0
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: ================================================================================
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: It took 0.00 seconds to summarize the package selections.
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/zliu/Downloads/napari-macOS-arm64.pkg#prepare_installation.pkg
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/zliu/Downloads/napari-macOS-arm64.pkg#shortcuts.pkg
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/zliu/Downloads/napari-macOS-arm64.pkg#cacheclean.pkg
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: Set authorization level to root for session
Dec 19 10:29:27 CZIMACOS3562 Installer[24351]: Authorization is being checked, waiting until authorization arrives.
Dec 19 10:29:28 CZIMACOS3562 Installer[24351]: Administrator authorization granted.
Dec 19 10:29:28 CZIMACOS3562 Installer[24351]: Packages have been authorized for installation.
Dec 19 10:29:28 CZIMACOS3562 Installer[24351]: Will use PK session
Dec 19 10:29:28 CZIMACOS3562 Installer[24351]: Using authorization level of root for IFPKInstallElement
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: Starting installation:
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: Configuring volume "Macintosh HD"
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: Preparing disk for local booted install.
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: Free space on "Macintosh HD": 391.02 GB (391017336832 bytes).
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: Create temporary directory "/var/folders/jt/p42nnqj559j6hw4zkcjx8sn00000gq/T//Install.243510ESiz9"
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: IFPKInstallElement (4 packages)
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: Current Path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Dec 19 10:29:29 CZIMACOS3562 installd[6596]: PackageKit: Adding client PKInstallDaemonClient pid=24351, uid=503 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Dec 19 10:29:29 CZIMACOS3562 Installer[24351]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Dec 19 10:29:29 CZIMACOS3562 installd[6596]: PackageKit: Set reponsibility for install to 24351
Dec 19 10:29:29 CZIMACOS3562 installd[6596]: PackageKit: Hosted team responsibility for install set to team:(7WAT66VT96)
Dec 19 10:29:29 CZIMACOS3562 installd[6596]: PackageKit: ----- Begin install -----
Dec 19 10:29:29 CZIMACOS3562 installd[6596]: PackageKit: request=PKInstallRequest <4 packages, destination=/>
Dec 19 10:29:29 CZIMACOS3562 installd[6596]: PackageKit: packages=(
	    "PKLeopardPackage <id=org.napari.pkg.prepare_installation, version=0.4.17rc4.dev123_gb5696770, url=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#prepare_installation.pkg>",
	    "PKLeopardPackage <id=org.napari.pkg.shortcuts, version=0, url=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#shortcuts.pkg>",
	    "PKLeopardPackage <id=org.napari.pkg.run_installation, version=0, url=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg>",
	    "PKLeopardPackage <id=org.napari.pkg.cacheclean, version=0, url=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#cacheclean.pkg>"
	)
Dec 19 10:29:30 CZIMACOS3562 installd[6596]: PackageKit: Will do receipt-based obsoleting for package identifier org.napari.pkg.cacheclean (prefix path=/)
Dec 19 10:29:31 CZIMACOS3562 installd[6596]: PackageKit: Extracting file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#prepare_installation.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A616CBC5-9F49-47A2-9983-48D9125CE4DD.activeSandbox/Root/Library, uid=0)
Dec 19 10:29:32 CZIMACOS3562 installd[6596]: PackageKit: Extracting file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#shortcuts.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A616CBC5-9F49-47A2-9983-48D9125CE4DD.activeSandbox/Root/Library, uid=0)
Dec 19 10:29:32 CZIMACOS3562 installd[6596]: PackageKit: Extracting file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A616CBC5-9F49-47A2-9983-48D9125CE4DD.activeSandbox/Root/Library, uid=0)
Dec 19 10:29:32 CZIMACOS3562 installd[6596]: PackageKit: Extracting file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#cacheclean.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A616CBC5-9F49-47A2-9983-48D9125CE4DD.activeSandbox/Root/Library, uid=0)
Dec 19 10:29:32 CZIMACOS3562 installd[6596]: PackageKit: prevent user idle system sleep
Dec 19 10:29:32 CZIMACOS3562 installd[6596]: PackageKit: suspending backupd
Dec 19 10:29:32 CZIMACOS3562 installd[6596]: PackageKit (package_script_service): Preparing to execute script "./preinstall" in /private/tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.prepare_installation.akyA2g
Dec 19 10:29:32 CZIMACOS3562 package_script_service[31549]: PackageKit: Preparing to execute script "preinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.prepare_installation.akyA2g
Dec 19 10:29:32 CZIMACOS3562 package_script_service[31549]: Set responsibility to pid: 24351, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Dec 19 10:29:32 CZIMACOS3562 package_script_service[31549]: Hosted team responsibility for script set to team:(7WAT66VT96)
Dec 19 10:29:32 CZIMACOS3562 package_script_service[31549]: PackageKit: Executing script "preinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.prepare_installation.akyA2g
Dec 19 10:29:32 CZIMACOS3562 install_monitor[24358]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: ./preinstall: PREFIX=/Library/napari-0.4.17rc4.dev123+gb5696770
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: PackageKit: Hosted team responsible for script has been cleared.
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: Responsibility set back to self.
Dec 19 10:29:33 CZIMACOS3562 installd[6596]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/A616CBC5-9F49-47A2-9983-48D9125CE4DD.sandboxTrash for sandbox /Library/InstallerSandboxes/.PKInstallSandboxManager/A616CBC5-9F49-47A2-9983-48D9125CE4DD.activeSandbox
Dec 19 10:29:33 CZIMACOS3562 installd[6596]: PackageKit: Shoving /Library/InstallerSandboxes/.PKInstallSandboxManager/A616CBC5-9F49-47A2-9983-48D9125CE4DD.activeSandbox/Root (1 items) to /
Dec 19 10:29:33 CZIMACOS3562 softwareupdated[307]: Event handler called with flags: 103
Dec 19 10:29:33 CZIMACOS3562 installd[6596]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.prepare_installation.akyA2g
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: PackageKit: Preparing to execute script "postinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.prepare_installation.akyA2g
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: Set responsibility to pid: 24351, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: Hosted team responsibility for script set to team:(7WAT66VT96)
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.prepare_installation.akyA2g
Dec 19 10:29:33 CZIMACOS3562 package_script_service[31549]: ./postinstall: PREFIX=/Library/napari-0.4.17rc4.dev123+gb5696770
Dec 19 10:29:33 CZIMACOS3562 root[24366]: Preparing packages...
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: PackageKit: Hosted team responsible for script has been cleared.
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: Responsibility set back to self.
Dec 19 10:29:59 CZIMACOS3562 installd[6596]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.shortcuts.Nkoehp
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: PackageKit: Preparing to execute script "postinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.shortcuts.Nkoehp
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: Set responsibility to pid: 24351, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: Hosted team responsibility for script set to team:(7WAT66VT96)
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.shortcuts.Nkoehp
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: ./postinstall: + PREFIX=/Library/napari-0.4.17rc4.dev123+gb5696770
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: ./postinstall: ++ cd /Library/napari-0.4.17rc4.dev123+gb5696770
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: ./postinstall: ++ pwd
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: ./postinstall: + PREFIX=/Library/napari-0.4.17rc4.dev123+gb5696770
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: ./postinstall: + touch /Library/napari-0.4.17rc4.dev123+gb5696770/pkgs/user_wants_shortcuts
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: PackageKit: Hosted team responsible for script has been cleared.
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: Responsibility set back to self.
Dec 19 10:29:59 CZIMACOS3562 installd[6596]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.run_installation.s13u3h
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: PackageKit: Preparing to execute script "postinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.run_installation.s13u3h
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: Set responsibility to pid: 24351, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: Hosted team responsibility for script set to team:(7WAT66VT96)
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.7EqHsK/Scripts/org.napari.pkg.run_installation.s13u3h
Dec 19 10:29:59 CZIMACOS3562 package_script_service[31549]: ./postinstall: PREFIX=/Library/napari-0.4.17rc4.dev123+gb5696770
Dec 19 10:29:59 CZIMACOS3562 root[24396]: Installing packages. This might take a few minutes.
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: Traceback (most recent call last):
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/models/version.py", line 11, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: ModuleNotFoundError: No module named 'tlz'
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: During handling of the above exception, another exception occurred:
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: Traceback (most recent call last):
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/exceptions.py", line 1129, in __call__
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/main.py", line 86, in main_subshell
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/conda_argparse.py", line 91, in do_call
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "importlib/__init__.py", line 127, in import_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/main_install.py", line 8, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/install.py", line 10, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/common.py", line 19, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/models/match_spec.py", line 21, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/models/version.py", line 13, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: ModuleNotFoundError: No module named 'conda._vendor.toolz.functoolz'
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: During handling of the above exception, another exception occurred:
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: Traceback (most recent call last):
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/models/version.py", line 11, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: ModuleNotFoundError: No module named 'tlz'
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: During handling of the above exception, another exception occurred:
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: Traceback (most recent call last):
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "entry_point.py", line 125, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/main.py", line 129, in main
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/exceptions.py", line 1429, in conda_exception_handler
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/exceptions.py", line 1132, in __call__
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/exceptions.py", line 1172, in handle_exception
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/exceptions.py", line 1183, in handle_unexpected_exception
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/exceptions.py", line 1245, in print_unexpected_error_report
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/main_info.py", line 14, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/cli/common.py", line 19, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/models/match_spec.py", line 21, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall:   File "conda/models/version.py", line 13, in <module>
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: ModuleNotFoundError: No module named 'conda._vendor.toolz.functoolz'
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: ./postinstall: [24398] Failed to execute script 'entry_point' due to unhandled exception!
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: PackageKit: Hosted team responsible for script has been cleared.
Dec 19 10:30:05 CZIMACOS3562 package_script_service[31549]: Responsibility set back to self.
Dec 19 10:30:05 CZIMACOS3562 install_monitor[24358]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: releasing backupd
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: allow user idle system sleep
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “napari-macOS-arm64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg, PKInstallPackageIdentifier=org.napari.pkg.run_installation, NSLocalizedDescription=An error occurred while running scripts from the package “napari-macOS-arm64.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cnapari-macOS-arm64.pkg\U201d.";
	    NSURL = "file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg";
	    PKInstallPackageIdentifier = "org.napari.pkg.run_installation";
	}
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Cleared responsibility for install from 24351.
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Cleared permissions on Installer.app
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Hosted team responsible for install has been cleared.
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Running idle tasks
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Done with sandbox removals
Dec 19 10:30:06 CZIMACOS3562 Installer[24351]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “napari-macOS-arm64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/zliu/Downloads/napari-macOS-arm64.pkg#run_installation.pkg, PKInstallPackageIdentifier=org.napari.pkg.run_installation, NSLocalizedDescription=An error occurred while running scripts from the package “napari-macOS-arm64.pkg”.}
Dec 19 10:30:06 CZIMACOS3562 installd[6596]: PackageKit: Removing client PKInstallDaemonClient pid=24351, uid=503 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Dec 19 10:30:07 CZIMACOS3562 Installer[24351]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Dec 19 10:30:07 CZIMACOS3562 Installer[24351]: IFDInstallController 3A5B9A0 state = 8
Dec 19 10:30:07 CZIMACOS3562 Installer[24351]: Displaying 'Install Failed' UI.
Dec 19 10:30:07 CZIMACOS3562 Installer[24351]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

the tree is too large to post here, but in the end it reports:
`10375 directories, 65263 files`

**Comment by jaimergp** [comment] 2022-12-19 18:35
I am downloading to see if I can reproduce, but it looks like a system `conda` is getting on the way. Let me check a couple things and I'll get back to you.

**Comment by jaimergp** [comment] 2022-12-19 18:43
Ok, I can reproduce on my machine. Uncanny why it seems to work on CI. I've also seen a shortcuts issue on Linux.

**Comment by jaimergp** [comment] 2022-12-19 18:58
Ah, I know why. I build the osx-arm64 conda-standalone executables locally because `pyinstaller` cannot cross-compile. I might have made a mistake, but that's actually good news because the fix is simple and explains why Intel CI does not fail (those conda-standalone exes are built on CI).

**Comment by jaimergp** [comment] 2022-12-20 09:56
New conda-standalones are uploaded now. Next nightlies should be fixed.

**Closed** 2022-12-20 17:29 UTC
Labels: bundle

**Comment by jaimergp** [comment] 2022-12-21 08:49
Confirmed fixed.
